//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freelancing
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public int Client_id { get; set; }
        public int User_id { get; set; }
        public string Company_name { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
