//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freelancing
{
    using System;
    using System.Collections.Generic;
    
    public partial class Freelancers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Freelancers()
        {
            this.Posts = new HashSet<Posts>();
        }
    
        public int Freelancer_id { get; set; }
        public int User_id { get; set; }
        public string Experience { get; set; }
        public string Linkedin_link { get; set; }
        public Nullable<int> Category_id { get; set; }
        public byte[] CV { get; set; }
    
        public virtual Categories Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Posts> Posts { get; set; }
        public virtual Users Users { get; set; }
    }
}
