//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freelancing
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posts
    {
        public int Post_id { get; set; }
        public int Freelancer_id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Category_id { get; set; }
        public byte[] Image { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Freelancers Freelancers { get; set; }
    }
}
